
test_that("wk classes are vctrs", {
  expect_true(vctrs::vec_is(wkt()))
  expect_true(vctrs::vec_is(wkb()))
  expect_true(vctrs::vec_is(wksxp()))
  expect_true(vctrs::vec_is(xy()))
  expect_true(vctrs::vec_is(xyz()))
  expect_true(vctrs::vec_is(xym()))
  expect_true(vctrs::vec_is(xyzm()))
  expect_true(vctrs::vec_is(rct()))
})

test_that("wk classes can be proxied and restored", {
  expect_identical(vctrs::vec_restore(vctrs::vec_proxy(wkt()), wkt()), wkt())
  expect_identical(vctrs::vec_restore(vctrs::vec_proxy(wkb()), wkb()), wkb())
  expect_identical(vctrs::vec_restore(vctrs::vec_proxy(wksxp()), wksxp()), wksxp())
  expect_identical(vctrs::vec_restore(vctrs::vec_proxy(xy()), xy()), xy())
  expect_identical(vctrs::vec_restore(vctrs::vec_proxy(xyz()), xyz()), xyz())
  expect_identical(vctrs::vec_restore(vctrs::vec_proxy(xym()), xym()), xym())
  expect_identical(vctrs::vec_restore(vctrs::vec_proxy(xyzm()), xyzm()), xyzm())
  expect_identical(vctrs::vec_restore(vctrs::vec_proxy(rct()), rct()), rct())
})

test_that("vctrs wkb implementation works", {
  expect_true(vctrs::vec_is(wkb()))
  expect_identical(vctrs::vec_size(wkb()), 0L)
  expect_identical(vctrs::vec_cast(wkb(), wkb()), wkb())
  expect_identical(vctrs::vec_cast(wkt(), wkb()), wkb())
  expect_identical(vctrs::vec_cast(wksxp(), wkb()), wkb())
  expect_identical(vctrs::vec_proxy(wkb(crs = NULL)), list())
  expect_identical(vctrs::vec_restore(list(), wkb()), wkb())
  expect_identical(vctrs::vec_c(wkb(), wkb()), wkb())
  expect_identical(vctrs::vec_c(wkb(), wkt()), wkt())
  expect_identical(vctrs::vec_c(wkb(), wksxp()), wksxp())
  expect_identical(vctrs::vec_c(wkb(), xy()), wkb())
  expect_identical(vctrs::vec_c(wkb(), xyz()), wkb())
  expect_identical(vctrs::vec_c(wkb(), xym()), wkb())
  expect_identical(vctrs::vec_c(wkb(), xyzm()), wkb())
  expect_identical(vctrs::vec_c(wkb(), rct()), wkb())
})

test_that("vctrs wkt implementation works", {
  expect_true(vctrs::vec_is(wkt()))
  expect_identical(vctrs::vec_size(wkt()), 0L)
  expect_identical(vctrs::vec_cast(wkt(), wkt()), wkt())
  expect_identical(vctrs::vec_cast(wkb(), wkt()), wkt())
  expect_identical(vctrs::vec_cast(wksxp(), wkt()), wkt())
  expect_identical(vctrs::vec_proxy(wkt(crs = NULL)), character())
  expect_identical(vctrs::vec_restore(character(), wkt()), wkt())
  expect_identical(vctrs::vec_c(wkt(), wkt()), wkt())
  expect_identical(vctrs::vec_c(wkt(), wkb()), wkt())
  expect_identical(vctrs::vec_c(wkt(), wksxp()), wksxp())
  expect_identical(vctrs::vec_c(wkt(), xy()), wkt())
  expect_identical(vctrs::vec_c(wkt(), xyz()), wkt())
  expect_identical(vctrs::vec_c(wkt(), xym()), wkt())
  expect_identical(vctrs::vec_c(wkt(), xyzm()), wkt())
  expect_identical(vctrs::vec_c(wkt(), rct()), wkt())
})

test_that("vctrs wksxp implementation works", {
  expect_true(vctrs::vec_is(wksxp()))
  expect_identical(vctrs::vec_size(wksxp()), 0L)
  expect_identical(vctrs::vec_cast(wksxp(), wksxp()), wksxp())
  expect_identical(vctrs::vec_cast(wkb(), wksxp()), wksxp())
  expect_identical(vctrs::vec_cast(wkt(), wksxp()), wksxp())
  expect_identical(vctrs::vec_proxy(wksxp(crs = NULL)), list())
  expect_identical(vctrs::vec_restore(list(), wksxp()), wksxp())
  expect_identical(vctrs::vec_c(wksxp(), wksxp()), wksxp())
  expect_identical(vctrs::vec_c(wksxp(), wkt()), wksxp())
  expect_identical(vctrs::vec_c(wksxp(), wkb()), wksxp())
  expect_identical(vctrs::vec_c(wksxp(), xy()), wksxp())
  expect_identical(vctrs::vec_c(wksxp(), xyz()), wksxp())
  expect_identical(vctrs::vec_c(wksxp(), xym()), wksxp())
  expect_identical(vctrs::vec_c(wksxp(), xyzm()), wksxp())
  expect_identical(vctrs::vec_c(wksxp(), rct()), wksxp())
})

test_that("vctrs xy implementation works", {
  expect_true(vctrs::vec_is(xy()))
  expect_identical(vctrs::vec_size(xy()), 0L)
  expect_identical(vctrs::vec_cast(wkt(), xy()), xy())
  expect_identical(vctrs::vec_cast(wkb(), xy()), xy())
  expect_identical(vctrs::vec_cast(wksxp(), xy()), xy())
  expect_identical(vctrs::vec_cast(xy(), xy()), xy())
  expect_identical(vctrs::vec_cast(xyz(), xy()), xy())
  expect_identical(vctrs::vec_cast(xym(), xy()), xy())
  expect_identical(vctrs::vec_cast(xyzm(), xy()), xy())
  expect_error(vctrs::vec_cast(rct(), xy()), class = "vctrs_error_incompatible_type")
  expect_identical(vctrs::vec_proxy(xy(crs = NULL)), data.frame(x = double(), y = double()))
  expect_identical(vctrs::vec_restore(data.frame(x = double(), y = double()), xy()), xy())
  expect_identical(vctrs::vec_c(xy(), wkt()), wkt())
  expect_identical(vctrs::vec_c(xy(), wkb()), wkb())
  expect_identical(vctrs::vec_c(xy(), wksxp()), wksxp())
  expect_identical(vctrs::vec_c(xy(), xy()), xy())
  expect_identical(vctrs::vec_c(xy(), xyz()), xyz())
  expect_identical(vctrs::vec_c(xy(), xym()), xym())
  expect_identical(vctrs::vec_c(xy(), xyzm()), xyzm())
  expect_identical(vctrs::vec_c(xy(), rct()), wkb())
})

test_that("vec_c() propagates the crs attribute", {
  expect_identical(
    vctrs::vec_c(wkt(crs = 1234), wkt(crs = 1234)),
    wkt(crs = 1234)
  )

  expect_identical(
    vctrs::vec_c(wkb(crs = 1234), wkb(crs = 1234)),
    wkb(crs = 1234)
  )

  expect_identical(
    vctrs::vec_c(wksxp(crs = 1234), wksxp(crs = 1234)),
    wksxp(crs = 1234)
  )
})
