# Generated by cpp11: do not edit by hand

wk_cpp_handle_wkt <- function(wkt, xptr, buffer_size, reveal_size) {
  .Call(`_wk_wk_cpp_handle_wkt`, wkt, xptr, buffer_size, reveal_size)
}

wk_cpp_wkt_writer <- function(precision, trim) {
  .Call(`_wk_wk_cpp_wkt_writer`, precision, trim)
}

wk_cpp_wkt_formatter <- function(precision, trim, max_coords) {
  .Call(`_wk_wk_cpp_wkt_formatter`, precision, trim, max_coords)
}
