# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_format_wkb <- function(wkb, maxCoords) {
    .Call(`_wk_cpp_format_wkb`, wkb, maxCoords)
}

cpp_format_wkt <- function(wkt, maxCoords) {
    .Call(`_wk_cpp_format_wkt`, wkt, maxCoords)
}

cpp_format_wksxp <- function(wksxp, maxCoords) {
    .Call(`_wk_cpp_format_wksxp`, wksxp, maxCoords)
}

cpp_problems_wkb <- function(wkb) {
    .Call(`_wk_cpp_problems_wkb`, wkb)
}

cpp_problems_wkt <- function(wkt) {
    .Call(`_wk_cpp_problems_wkt`, wkt)
}

cpp_problems_wksxp <- function(wksxp) {
    .Call(`_wk_cpp_problems_wksxp`, wksxp)
}

cpp_wkb_translate_wkt <- function(wkb, includeZ, includeM, includeSRID, precision, trim) {
    .Call(`_wk_cpp_wkb_translate_wkt`, wkb, includeZ, includeM, includeSRID, precision, trim)
}

cpp_wkb_translate_wkb <- function(wkb, includeZ, includeM, includeSRID, endian, bufferSize) {
    .Call(`_wk_cpp_wkb_translate_wkb`, wkb, includeZ, includeM, includeSRID, endian, bufferSize)
}

cpp_wkb_translate_wksxp <- function(wkb, includeZ, includeM, includeSRID) {
    .Call(`_wk_cpp_wkb_translate_wksxp`, wkb, includeZ, includeM, includeSRID)
}

cpp_wkt_translate_wkt <- function(wkt, includeZ, includeM, includeSRID, precision, trim) {
    .Call(`_wk_cpp_wkt_translate_wkt`, wkt, includeZ, includeM, includeSRID, precision, trim)
}

cpp_wkt_translate_wkb <- function(wkt, includeZ, includeM, includeSRID, endian, bufferSize) {
    .Call(`_wk_cpp_wkt_translate_wkb`, wkt, includeZ, includeM, includeSRID, endian, bufferSize)
}

cpp_wkt_translate_wksxp <- function(wkt, includeZ, includeM, includeSRID) {
    .Call(`_wk_cpp_wkt_translate_wksxp`, wkt, includeZ, includeM, includeSRID)
}

cpp_wksxp_translate_wkt <- function(wksexp, includeZ, includeM, includeSRID, precision, trim) {
    .Call(`_wk_cpp_wksxp_translate_wkt`, wksexp, includeZ, includeM, includeSRID, precision, trim)
}

cpp_wksxp_translate_wkb <- function(wksexp, includeZ, includeM, includeSRID, endian, bufferSize) {
    .Call(`_wk_cpp_wksxp_translate_wkb`, wksexp, includeZ, includeM, includeSRID, endian, bufferSize)
}

cpp_wksxp_translate_wksxp <- function(wksexp, includeZ, includeM, includeSRID) {
    .Call(`_wk_cpp_wksxp_translate_wksxp`, wksexp, includeZ, includeM, includeSRID)
}

