# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_problems_wkb <- function(wkb) {
    .Call(`_wk_cpp_problems_wkb`, wkb)
}

cpp_translate_wkb_wkt <- function(wkb, includeZ, includeM, includeSRID, precision, trim) {
    .Call(`_wk_cpp_translate_wkb_wkt`, wkb, includeZ, includeM, includeSRID, precision, trim)
}

cpp_translate_wkb_wkb <- function(wkb, includeZ, includeM, includeSRID, endian, bufferSize) {
    .Call(`_wk_cpp_translate_wkb_wkb`, wkb, includeZ, includeM, includeSRID, endian, bufferSize)
}

